use_frameworks!

platform :ios, '8.0'

target 'GCWKWebViewJSBridge_Example' do
  pod 'GCWKWebViewJSBridge', :path => '../GCWKWebViewJSBridge.podspec'

  target 'GCWKWebViewJSBridge_Tests' do
    inherit! :search_paths


  end
end
